title: Ahmed Sabry
logo: assets/img/headshot.jpeg
email: ahmedmsabry2000@gmail.com
description: |
  Electrical, Software, and AI/ML engineering enthusiast with industry experience in power systems, 
  embedded development, and data-driven optimization. Passionate about leveraging technology to 
  solve complex real-world problems.
github_username: ahmedmsabry2000

theme: jekyll-theme-minimal
